version: "3.0"
services:
  grafana:
    image: grafana/grafana:8.0.7
    #image: grafana/grafana:10.1.1
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/lib/grafana/plugins/briangann-datatable-panel
    environment:
      - TERM=linux
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=briangann-datatable-panel
