version: '3.0'

services:
  grafana:
    container_name: 'briangann-datatable-panel'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.3.4}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/briangann-datatable-panel
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=briangann-datatable-panel
