version: '3.0'

services:
  grafana:
    container_name: 'briangann-datatable-panel'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.3.16}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/briangann-datatable-panel
      - ./provisioning:/etc/grafana/provisioning
