import { defineConfig } from 'eslint/config';
import baseConfig from './.config/eslint.config.mjs';

export default defineConfig([
  {
    ignores: [
      '**/logs',
      '**/*.log',
      '**/npm-debug.log*',
      '**/yarn-debug.log*',
      '**/yarn-error.log*',
      '**/.pnpm-debug.log*',
      '**/node_modules/',
      '**/pids',
      '**/*.pid',
      '**/*.seed',
      '**/*.pid.lock',
      '**/lib-cov',
      '**/coverage',
      '**/dist/',
      '**/artifacts/',
      '**/work/',
      '**/ci/',
      '**/e2e-results/',
      '**/cypress/videos',
      '**/cypress/report.json',
      '**/.idea',
      '**/.DS_Store',
      '**/.eslintcache',
      'playwright/.auth/admin.json',
      'playwright/.auth/grafanaAPICredentials.json',
      '**/playwright-report',
      '**/.stignore',
      '**/.stfolder/',
      '**/provisioning-private/',
      '**/importable/',
      '**/test-results/',
      '**/TODO.md',
    ],
  },
  ...baseConfig,
]);
